---
- name: bootstrap deploy app to docker
  hosts: docker

  tasks:
  - name: deploy jenkins
    docker: 
      name: "jenkins"
      image: "jenkins:1.593"
      detach: true
      pull: always
      state: reloaded

