---
- name: bootstrap deploy app to docker
  hosts: docker

  tasks:
  - name: deploy jenkins
    docker:
      name: "jenkins" 
      image: "jenkins:1.590"
      detach: true
      pull: always
      state: reloaded

